### PR TITLE
Add install instructions

### PR DESCRIPTION
**Pull request by minhducsun2002**
Due to some people being not familiar with GNU autoconf, an installation instruction is included.

### CODE REVIEW

**Review by ncopa — COMMENTED** [review]
we have an INSTALL document, which I assume is worthless?

**Comment by minhducsun2002** [comment]
It's missing some instructions. For example, [INSTALL](https://github.com/ncopa/xfce-polkit/blob/master/INSTALL) doesn't mention the fact `aclocal`, `autoconf` and `automake` is used in the compilation process.

Anyway, I suggest you to provide your users with specific compilation (and installation) instructions. That might keep you from running into issues with people who doesn't compile in the way you intended.

**Comment by ncopa** [comment]
Thank you!

**Comment by minhducsun2002** [comment]
You're welcome.

Nevertheless, I do use [`xfce-polkit`](https://github.com/ncopa/xfce-polkit) and [`xfce-bluetooth`](https://github.com/ncopa/xfce-bluetooth)... and I think that's a little thing I could do, as a way of expressing my gratitude to you, the developer who creates (and maintains) fundamental parts in my desktop environment.

**Comment by minhducsun2002** [comment]
Also, may I have your permission to host this software on a Launchpad PPA?

**Pull request merged**
